import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";
import MobileNav from "@/components/shared/MobileNav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStore = await headers();
  const host = headerStore.get("host") ?? "";
  const isPrimary = host.includes("primary");
  const themeClass = isPrimary ? "theme-primary" : "theme-urgent";
  const currentTenant = isPrimary ? "primary-care" : "urgent-care";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${themeClass}`}
      >
        <Header currentTenant={currentTenant} />
        {children}
        <Footer />
        <MobileNav />
      </body>
    </html>
  );
}
